// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsdlhizignrvweuozyqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZGxoaXppZ25ydndldW96eXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcyNDYxNTMsImV4cCI6MjA4MjgyMjE1M30.BKtkCFyk3f3wMQUyBTci2Qt1p1JOmV66h5SPq2b_2x4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});