// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tebrdzsivvnakzgqxmht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlYnJkenNpdnZuYWt6Z3F4bWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjUzNTQsImV4cCI6MjA2NjQwMTM1NH0.AKYbgymo6JP7-4ZaubuQanJLGWlJJS2SPsFY2EDmcDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);